import type * as vscode from "vscode";

const COMMON_CAPABILITIES: vscode.LanguageModelChatCapabilities = {
  imageInput: true,
  toolCalling: true,
};

const GEMINI_LIMITS = { maxInputTokens: 1_048_576, maxOutputTokens: 65_536 };
const GEMINI_PRO_LIMITS = { maxInputTokens: 1_048_576, maxOutputTokens: 65_535 };
const CLAUDE_LIMITS = { maxInputTokens: 200_000, maxOutputTokens: 64_000 };

const VERSION = "2026-01-08";

export const MODELS: vscode.LanguageModelChatInformation[] = [
  {
    id: "antigravity-gemini-3-pro",
    name: "Gemini 3 Pro",
    family: "gemini-3-pro",
    version: VERSION,
    detail: "Antigravity quota",
    maxInputTokens: GEMINI_PRO_LIMITS.maxInputTokens,
    maxOutputTokens: GEMINI_PRO_LIMITS.maxOutputTokens,
    capabilities: COMMON_CAPABILITIES,
  },
  {
    id: "antigravity-gemini-3-pro-low",
    name: "Gemini 3 Pro Low",
    family: "gemini-3-pro",
    version: VERSION,
    detail: "Antigravity quota (low thinking)",
    maxInputTokens: GEMINI_PRO_LIMITS.maxInputTokens,
    maxOutputTokens: GEMINI_PRO_LIMITS.maxOutputTokens,
    capabilities: COMMON_CAPABILITIES,
  },
  {
    id: "antigravity-gemini-3-pro-high",
    name: "Gemini 3 Pro High",
    family: "gemini-3-pro",
    version: VERSION,
    detail: "Antigravity quota (high thinking)",
    maxInputTokens: GEMINI_PRO_LIMITS.maxInputTokens,
    maxOutputTokens: GEMINI_PRO_LIMITS.maxOutputTokens,
    capabilities: COMMON_CAPABILITIES,
  },
  {
    id: "antigravity-gemini-3-flash",
    name: "Gemini 3 Flash",
    family: "gemini-3-flash",
    version: VERSION,
    detail: "Antigravity quota",
    maxInputTokens: GEMINI_LIMITS.maxInputTokens,
    maxOutputTokens: GEMINI_LIMITS.maxOutputTokens,
    capabilities: COMMON_CAPABILITIES,
  },
  {
    id: "antigravity-gemini-3-flash-minimal",
    name: "Gemini 3 Flash Minimal",
    family: "gemini-3-flash",
    version: VERSION,
    detail: "Antigravity quota (minimal thinking)",
    maxInputTokens: GEMINI_LIMITS.maxInputTokens,
    maxOutputTokens: GEMINI_LIMITS.maxOutputTokens,
    capabilities: COMMON_CAPABILITIES,
  },
  {
    id: "antigravity-gemini-3-flash-low",
    name: "Gemini 3 Flash Low",
    family: "gemini-3-flash",
    version: VERSION,
    detail: "Antigravity quota (low thinking)",
    maxInputTokens: GEMINI_LIMITS.maxInputTokens,
    maxOutputTokens: GEMINI_LIMITS.maxOutputTokens,
    capabilities: COMMON_CAPABILITIES,
  },
  {
    id: "antigravity-gemini-3-flash-medium",
    name: "Gemini 3 Flash Medium",
    family: "gemini-3-flash",
    version: VERSION,
    detail: "Antigravity quota (medium thinking)",
    maxInputTokens: GEMINI_LIMITS.maxInputTokens,
    maxOutputTokens: GEMINI_LIMITS.maxOutputTokens,
    capabilities: COMMON_CAPABILITIES,
  },
  {
    id: "antigravity-gemini-3-flash-high",
    name: "Gemini 3 Flash High",
    family: "gemini-3-flash",
    version: VERSION,
    detail: "Antigravity quota (high thinking)",
    maxInputTokens: GEMINI_LIMITS.maxInputTokens,
    maxOutputTokens: GEMINI_LIMITS.maxOutputTokens,
    capabilities: COMMON_CAPABILITIES,
  },
  {
    id: "antigravity-claude-sonnet-4-5",
    name: "Claude Sonnet 4.5",
    family: "claude-sonnet-4-5",
    version: VERSION,
    detail: "Antigravity quota",
    maxInputTokens: CLAUDE_LIMITS.maxInputTokens,
    maxOutputTokens: CLAUDE_LIMITS.maxOutputTokens,
    capabilities: COMMON_CAPABILITIES,
  },
  {
    id: "antigravity-claude-sonnet-4-5-thinking",
    name: "Claude Sonnet 4.5 Thinking",
    family: "claude-sonnet-4-5",
    version: VERSION,
    detail: "Antigravity quota (thinking)",
    maxInputTokens: CLAUDE_LIMITS.maxInputTokens,
    maxOutputTokens: CLAUDE_LIMITS.maxOutputTokens,
    capabilities: COMMON_CAPABILITIES,
  },
  {
    id: "antigravity-claude-sonnet-4-5-thinking-low",
    name: "Claude Sonnet 4.5 Thinking Low",
    family: "claude-sonnet-4-5",
    version: VERSION,
    detail: "Antigravity quota (thinking low)",
    maxInputTokens: CLAUDE_LIMITS.maxInputTokens,
    maxOutputTokens: CLAUDE_LIMITS.maxOutputTokens,
    capabilities: COMMON_CAPABILITIES,
  },
  {
    id: "antigravity-claude-sonnet-4-5-thinking-medium",
    name: "Claude Sonnet 4.5 Thinking Medium",
    family: "claude-sonnet-4-5",
    version: VERSION,
    detail: "Antigravity quota (thinking medium)",
    maxInputTokens: CLAUDE_LIMITS.maxInputTokens,
    maxOutputTokens: CLAUDE_LIMITS.maxOutputTokens,
    capabilities: COMMON_CAPABILITIES,
  },
  {
    id: "antigravity-claude-sonnet-4-5-thinking-high",
    name: "Claude Sonnet 4.5 Thinking High",
    family: "claude-sonnet-4-5",
    version: VERSION,
    detail: "Antigravity quota (thinking high)",
    maxInputTokens: CLAUDE_LIMITS.maxInputTokens,
    maxOutputTokens: CLAUDE_LIMITS.maxOutputTokens,
    capabilities: COMMON_CAPABILITIES,
  },
  {
    id: "antigravity-claude-opus-4-5-thinking",
    name: "Claude Opus 4.5 Thinking",
    family: "claude-opus-4-5",
    version: VERSION,
    detail: "Antigravity quota (thinking)",
    maxInputTokens: CLAUDE_LIMITS.maxInputTokens,
    maxOutputTokens: CLAUDE_LIMITS.maxOutputTokens,
    capabilities: COMMON_CAPABILITIES,
  },
  {
    id: "antigravity-claude-opus-4-5-thinking-low",
    name: "Claude Opus 4.5 Thinking Low",
    family: "claude-opus-4-5",
    version: VERSION,
    detail: "Antigravity quota (thinking low)",
    maxInputTokens: CLAUDE_LIMITS.maxInputTokens,
    maxOutputTokens: CLAUDE_LIMITS.maxOutputTokens,
    capabilities: COMMON_CAPABILITIES,
  },
  {
    id: "antigravity-claude-opus-4-5-thinking-medium",
    name: "Claude Opus 4.5 Thinking Medium",
    family: "claude-opus-4-5",
    version: VERSION,
    detail: "Antigravity quota (thinking medium)",
    maxInputTokens: CLAUDE_LIMITS.maxInputTokens,
    maxOutputTokens: CLAUDE_LIMITS.maxOutputTokens,
    capabilities: COMMON_CAPABILITIES,
  },
  {
    id: "antigravity-claude-opus-4-5-thinking-high",
    name: "Claude Opus 4.5 Thinking High",
    family: "claude-opus-4-5",
    version: VERSION,
    detail: "Antigravity quota (thinking high)",
    maxInputTokens: CLAUDE_LIMITS.maxInputTokens,
    maxOutputTokens: CLAUDE_LIMITS.maxOutputTokens,
    capabilities: COMMON_CAPABILITIES,
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    family: "gemini-2.5-flash",
    version: VERSION,
    detail: "Gemini CLI quota",
    maxInputTokens: GEMINI_LIMITS.maxInputTokens,
    maxOutputTokens: GEMINI_LIMITS.maxOutputTokens,
    capabilities: COMMON_CAPABILITIES,
  },
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    family: "gemini-2.5-pro",
    version: VERSION,
    detail: "Gemini CLI quota",
    maxInputTokens: GEMINI_PRO_LIMITS.maxInputTokens,
    maxOutputTokens: GEMINI_PRO_LIMITS.maxOutputTokens,
    capabilities: COMMON_CAPABILITIES,
  },
  {
    id: "gemini-3-flash-preview",
    name: "Gemini 3 Flash Preview",
    family: "gemini-3-flash",
    version: VERSION,
    detail: "Gemini CLI quota",
    maxInputTokens: GEMINI_LIMITS.maxInputTokens,
    maxOutputTokens: GEMINI_LIMITS.maxOutputTokens,
    capabilities: COMMON_CAPABILITIES,
  },
  {
    id: "gemini-3-pro-preview",
    name: "Gemini 3 Pro Preview",
    family: "gemini-3-pro",
    version: VERSION,
    detail: "Gemini CLI quota",
    maxInputTokens: GEMINI_PRO_LIMITS.maxInputTokens,
    maxOutputTokens: GEMINI_PRO_LIMITS.maxOutputTokens,
    capabilities: COMMON_CAPABILITIES,
  }
];
